Repository SaltyQuetzals/csce-315-team-2, pull requests merged in 2018-11, with the labels that each got.

#34 Added code to reduce the number of duplicate zombies generated.
  src/app.ts
  src/public/js/main.js
Labels: backend, bug, frontend

#35 Avoids obstacles when generating drops
  src/models/Game.ts
Labels: backend

#45 Modified sockets so that the initializers aren't all in update. Believe this solves issues for Firefox.
  src/public/js/main.js
Labels: bug, frontend

#46 Updated backend so it can handle when a player dies
  src/app.ts
Labels: backend

#49 Deployment
  package-lock.json
  package.json
  src/public/html/room.html
  src/public/js/main.js
Labels: backend

#52 Waiting room implementation
  src/app.ts
  src/controllers/RoomController.ts
  src/public/css/room.css
  src/public/html/room.html
  src/public/js/index.ts
  src/public/js/main.js
  src/public/js/waiting.ts
Labels: frontend

#53 Updated a bug fix in the main.js file
  src/public/js/main.js
Labels: bug, frontend

#58 Fixed Camera not following Zombie Issue
  src/public/js/main.js
Labels: frontend
